if @result1 == '2C-T-x' &&  @result2 == 'LSD' || @result2 == '2C-T-x' &&  @result1 == 'LSD'
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'Mushrooms' || @result2 == '2C-T-x' && @result1 == 'Mushrooms'
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'DMT' || @result2 == '2C-T-x' && @result1 == 'DMT'
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'Mescaline' || @result2 == '2C-T-x' && @result1 == 'Mescaline'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == 'DOx' || @result2 == '2C-T-x' && @result1 == 'DOx'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == 'NBOMes' || @result2 == '2C-T-x' && @result1 == 'NBOMes'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == '2C-x' || @result2 == '2C-x' && @result1 == '2C-T-x'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == '5-MeO-xxT' || @result2 == '2C-T-x' && @result1 == '5-MeO-xxT'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == 'Cannabis' || @result2 == '2C-T-x' && @result1 == 'Cannabis' 
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == 'Ketamine' || @result2 == '2C-T-x' && @result1 == 'Ketamine'
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'MXE' || @result2 == '2C-T-x' && @result1 == 'MXE'
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'DXM' || @result2 == '2C-T-x' && @result1 == 'DXM'
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'Nitrous' || @result2 == '2C-T-x' && @result2 == 'Nitrous'
    then final_value == 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'Amphetamines' || @result2 == '2C-T-x' && @result1 == 'Amphetamines'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == 'MDMA' || @result2 == '2C-T-x' && @result1 == 'MDMA' 
    then final_value = 'LR&S'
  elsif @result1 == '2C-T-x' && @result2 == 'Cocaine' || @result2 == '2C-T-x' && @result1 == 'Cocaine'
    then final_value = 'UNS'
  elsif @result1 == '2C-T-x' && @result2 == 'Caffeine' || @result2 == '2C-T-x' && @result1 == 'Caffeine'
    then final_value = 'LR&NS'
  elsif @result1 == '2C-T-x' && @result2 == 'Alcohol' || @result2 == '2C-T-x' && @result1 == 'Alcohol'
    then final_value = 'LR&D'
  elsif @result1 == '2C-T-x' && @result2 == 'GBH/GBL' || @result2 == '2C-T-x' && @result1 == 'GBH/GBL'
    then final_value = 'LR&D'
  elsif @result1 == '2C-T-x' && @result2 == 'Opioids' || @result2 == '2C-T-x' && @result1 == 'Opioids'
    then final_value = 'LR&NS'
  elsif @result1 == '2C-T-x' && @result2 == 'Tramadol' || @result2 == '2C-T-x' && @result1 == 'Tramadol'
    then final_value = 'UNS'
  elsif @result1 == '2C-T-x' && @result2 == 'Benzodiazepines' || @result2 == '2C-T-x' && @result1 == 'Benzodiazepines'
    then final_value = 'LR&D'
  elsif @result1 == '2C-T-x' && @result2 == 'MAOIs' || @result2 == '2C-T-x' && @result1 == 'MAOIs'
    then final_value = 'Caut'
  elsif @result1 == '2C-T-x' && @result2 == 'SSRIs' || @result2 == '2C-T-x' && @result1 == 'SSRIs' 
    then final_value = 'LR&D'
  end