class ApplicationController < ActionController::Base

  def test
    render({ :template => 'test.html.erb'})
  end

  def results
    require 'httparty'
    require 'json'
    @result1 = params.fetch("primary")
    @result2 = params.fetch("secondary")

    # LSD results
    final_value = ''
    if @result1 == 'LSD' &&  @result2 == 'Mushrooms' || @result2 == 'LSD' &&  @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'DMT' || @result2 == 'LSD' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'Mescaline' || @result2 == 'LSD' && @result1 == 'Mescaline'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'DOx' || @result2 == 'LSD' && @result1 == 'DOx'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'NBOMes' || @result2 == 'LSD' && @result1 == 'NBOMes'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == '2C-x' || @result2 == 'LSD' && @result1 == '2C-x'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == '2C-T-x' || @result2 == 'LSD' && @result1 == '2C-T-x'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == '5-MeO-xxT' || @result2 == 'LSD' && @result1 == '5-MeO-xxT'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'Cannabis' || @result2 == 'LSD' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == 'LSD' && @result2 == 'Ketamine' || @result2 == 'LSD' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'MXE' || @result2 == 'LSD' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'DXM' || @result2 == 'LSD' && @result1 == 'DXM'
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'Amphetamines' || @result2 == 'LSD' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == 'LSD' && @result2 == 'MDMA' || @result2 == 'LSD' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == 'LSD' && @result2 == 'Cocaine' || @result2 == 'LSD' && @result1 == 'Cocaine'
      then final_value = 'Caut'
    elsif @result1 == 'LSD' && @result2 == 'Caffeine' || @result2 == 'LSD' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == 'LSD' && @result2 == 'Alcohol' || @result2 == 'LSD' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == 'LSD' && @result2 == 'GBH/GBL' || @result2 == 'LSD' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == 'LSD' && @result2 == 'Opioids' || @result2 == 'LSD' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == 'LSD' && @result2 == 'Tramadol' || @result2 == 'LSD' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == 'LSD' && @result2 == 'Benzodiazepines' || @result2 == 'LSD' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'LSD' && @result2 == 'MAOIs' || @result2 == 'LSD' && @result1 == 'MAOIs'
      then final_value = 'LR&D'
    elsif @result1 == 'LSD' && @result2 == 'SSRIs' || @result2 == 'LSD' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == 'Mushrooms' &&  @result2 == 'LSD' || @result2 == 'Mushrooms' &&  @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'DMT' || @result2 == 'Mushrooms' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'Mescaline' || @result2 == 'Mushrooms' && @result1 == 'Mescaline'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'DOx' || @result2 == 'Mushrooms' && @result1 == 'DOx'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'NBOMes' || @result2 == 'Mushrooms' && @result1 == 'NBOMes'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == '2C-x' || @result2 == 'Mushrooms' && @result1 == '2C-x'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == '2C-T-x' || @result2 == 'Mushrooms' && @result1 == '2C-T-x'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == '5-MeO-xxT' || @result2 == 'Mushrooms' && @result1 == '5-MeO-xxT'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'Cannabis' || @result2 == 'Mushrooms' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == 'Mushrooms' && @result2 == 'Ketamine' || @result2 == 'Mushrooms' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'MXE' || @result2 == 'Mushrooms' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'DXM' || @result2 == 'Mushrooms' && @result1 == 'DXM'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'Amphetamines' || @result2 == 'Mushrooms' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == 'Mushrooms' && @result2 == 'MDMA' || @result2 == 'Mushrooms' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'Cocaine' || @result2 == 'Mushrooms' && @result1 == 'Cocaine'
      then final_value = 'Caut'
    elsif @result1 == 'Mushrooms' && @result2 == 'Caffeine' || @result2 == 'Mushrooms' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == 'Mushrooms' && @result2 == 'Alcohol' || @result2 == 'Mushrooms' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == 'Mushrooms' && @result2 == 'GBH/GBL' || @result2 == 'Mushrooms' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == 'Mushrooms' && @result2 == 'Opioids' || @result2 == 'Mushrooms' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == 'Mushrooms' && @result2 == 'Tramadol' || @result2 == 'Mushrooms' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == 'Mushrooms' && @result2 == 'Benzodiazepines' || @result2 == 'Mushrooms' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'Mushrooms' && @result2 == 'MAOIs' || @result2 == 'Mushrooms' && @result1 == 'MAOIs'
      then final_value = 'LR&S'
    elsif @result1 == 'Mushrooms' && @result2 == 'SSRIs' || @result2 == 'Mushrooms' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == 'DMT' &&  @result2 == 'LSD' || @result2 == 'DMT' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'Mushrooms' || @result2 == 'DMT' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'Mescaline' || @result2 == 'DMT' && @result1 == 'Mescaline'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'DOx' || @result2 == 'DMT' && @result1 == 'DOx'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'NBOMes' || @result2 == 'DMT' && @result1 == 'NBOMes'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == '2C-x' || @result2 == 'DMT' && @result1 == '2C-x'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == '2C-T-x' || @result2 == 'DMT' && @result1 == '2C-T-x'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == '5-MeO-xxT' || @result2 == 'DMT' && @result1 == '5-MeO-xxT'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'Cannabis' || @result2 == 'DMT' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == 'DMT' && @result2 == 'Ketamine' || @result2 == 'DMT' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'MXE' || @result2 == 'DMT' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'DXM' || @result2 == 'DMT' && @result1 == 'DXM'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'Amphetamines' || @result2 == 'DMT' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == 'DMT' && @result2 == 'MDMA' || @result2 == 'DMT' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'Cocaine' || @result2 == 'DMT' && @result1 == 'Cocaine'
      then final_value = 'Caut'
    elsif @result1 == 'DMT' && @result2 == 'Caffeine' || @result2 == 'DMT' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == 'DMT' && @result2 == 'Alcohol' || @result2 == 'DMT' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == 'DMT' && @result2 == 'GBH/GBL' || @result2 == 'DMT' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == 'DMT' && @result2 == 'Opioids' || @result2 == 'DMT' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == 'DMT' && @result2 == 'Tramadol' || @result2 == 'DMT' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == 'DMT' && @result2 == 'Benzodiazepines' || @result2 == 'DMT' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'DMT' && @result2 == 'MAOIs' || @result2 == 'DMT' && @result1 == 'MAOIs'
      then final_value = 'LR&S'
    elsif @result1 == 'DMT' && @result2 == 'SSRIs' || @result2 == 'DMT' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end
  
    if @result1 == 'Mescaline' &&  @result2 == 'LSD' || @result2 == 'Mescaline' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'Mushrooms' || @result2 == 'Mescaline' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'Mescaline' || @result2 == 'Mescaline' && @result1 == 'Mescaline'
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'DOx' || @result2 == 'Mescaline' && @result1 == 'DOx'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == 'NBOMes' || @result2 == 'Mescaline' && @result1 == 'NBOMes'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == '2C-x' || @result2 == 'Mescaline' && @result1 == '2C-x'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == '2C-T-x' || @result2 == 'Mescaline' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == '5-MeO-xxT' || @result2 == 'Mescaline' && @result1 == '5-MeO-xxT'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == 'Cannabis' || @result2 == 'Mescaline' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == 'Ketamine' || @result2 == 'Mescaline' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'MXE' || @result2 == 'Mescaline' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'DXM' || @result2 == 'Mescaline' && @result1 == 'DXM'
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'Amphetamines' || @result2 == 'Mescaline' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == 'MDMA' || @result2 == 'Mescaline' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == 'Mescaline' && @result2 == 'Cocaine' || @result2 == 'Mescaline' && @result1 == 'Cocaine'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == 'Caffeine' || @result2 == 'Mescaline' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == 'Mescaline' && @result2 == 'Alcohol' || @result2 == 'Mescaline' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == 'Mescaline' && @result2 == 'GBH/GBL' || @result2 == 'Mescaline' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == 'Mescaline' && @result2 == 'Opioids' || @result2 == 'Mescaline' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == 'Mescaline' && @result2 == 'Tramadol' || @result2 == 'Mescaline' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == 'Mescaline' && @result2 == 'Benzodiazepines' || @result2 == 'Mescaline' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'Mescaline' && @result2 == 'MAOIs' || @result2 == 'Mescaline' && @result1 == 'MAOIs'
      then final_value = 'Caut'
    elsif @result1 == 'Mescaline' && @result2 == 'SSRIs' || @result2 == 'Mescaline' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == 'DOx' &&  @result2 == 'LSD' || @result2 == 'DOx' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == 'DOx' && @result2 == 'Mushrooms' || @result2 == 'DOx' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'DOx' && @result2 == 'DMT' || @result2 == 'DOx' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == 'DOx' && @result2 == 'Mescaline' || @result2 == 'DOx' && @result1 == 'Mescaline'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'NBOMes' || @result2 == 'DOx' && @result1 == 'NBOMes'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == '2C-x' || @result2 == 'DOx' && @result1 == '2C-x'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == '2C-T-x' || @result2 == 'DOx' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == '5-MeO-xxT' || @result2 == 'DOx' && @result1 == '5-MeO-xxT'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'Cannabis' || @result2 == 'DOx' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'Ketamine' || @result2 == 'DOx' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'DOx' && @result2 == 'MXE' || @result2 == 'DOx' && @result1 == 'MXE'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'DXM' || @result2 == 'DOx' && @result1 == 'DXM'
      then final_value = 'UNS'
    elsif @result1 == 'DOx' && @result2 == 'Nitrous' || @result2 == 'DOx' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == 'DOx' && @result2 == 'Amphetamines' || @result2 == 'DOx' && @result1 == 'Amphetamines'
      then final_value = 'UNS'
    elsif @result1 == 'DOx' && @result2 == 'MDMA' || @result2 == 'DOx' && @result1 == 'MDMA' 
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'Cocaine' || @result2 == 'DOx' && @result1 == 'Cocaine'
      then final_value = 'UNS'
    elsif @result1 == 'DOx' && @result2 == 'Caffeine' || @result2 == 'DOx' && @result1 == 'Caffeine'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'Alcohol' || @result2 == 'DOx' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == 'DOx' && @result2 == 'GBH/GBL' || @result2 == 'DOx' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == 'DOx' && @result2 == 'Opioids' || @result2 == 'DOx' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == 'DOx' && @result2 == 'Tramadol' || @result2 == 'DOx' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == 'DOx' && @result2 == 'Benzodiazepines' || @result2 == 'DOx' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'DOx' && @result2 == 'MAOIs' || @result2 == 'DOx' && @result1 == 'MAOIs'
      then final_value = 'Caut'
    elsif @result1 == 'DOx' && @result2 == 'SSRIs' || @result2 == 'DOx' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == 'NBOMes' &&  @result2 == 'LSD' || @result2 == 'NBOMes' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == 'NBOMes' && @result2 == 'Mushrooms' || @result2 == 'NBOMes' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'NBOMes' && @result2 == 'DMT' || @result2 == 'NBOMes' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == 'NBOMes' && @result2 == 'Mescaline' || @result2 == 'NBOMes' && @result1 == 'Mescaline'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'DOx' || @result2 == 'NBOMes' && @result1 == 'DOx'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == '2C-x' || @result2 == 'NBOMes' && @result1 == '2C-x'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == '2C-T-x' || @result2 == 'NBOMes' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == '5-MeO-xxT' || @result2 == 'NBOMes' && @result1 == '5-MeO-xxT'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'Cannabis' || @result2 == 'NBOMes' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'Ketamine' || @result2 == 'NBOMes' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'NBOMes' && @result2 == 'MXE' || @result2 == 'NBOMes' && @result1 == 'MXE'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'DXM' || @result2 == 'NBOMes' && @result1 == 'DXM'
      then final_value = 'UNS'
    elsif @result1 == 'NBOMes' && @result2 == 'Nitrous' || @result2 == 'NBOMes' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == 'NBOMes' && @result2 == 'Amphetamines' || @result2 == 'NBOMes' && @result1 == 'Amphetamines'
      then final_value = 'UNS'
    elsif @result1 == 'NBOMes' && @result2 == 'MDMA' || @result2 == 'NBOMes' && @result1 == 'MDMA' 
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'Cocaine' || @result2 == 'NBOMes' && @result1 == 'Cocaine'
      then final_value = 'UNS'
    elsif @result1 == 'NBOMes' && @result2 == 'Caffeine' || @result2 == 'NBOMes' && @result1 == 'Caffeine'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'Alcohol' || @result2 == 'NBOMes' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == 'NBOMes' && @result2 == 'GBH/GBL' || @result2 == 'NBOMes' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == 'NBOMes' && @result2 == 'Opioids' || @result2 == 'NBOMes' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == 'NBOMes' && @result2 == 'Tramadol' || @result2 == 'NBOMes' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == 'NBOMes' && @result2 == 'Benzodiazepines' || @result2 == 'NBOMes' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'NBOMes' && @result2 == 'MAOIs' || @result2 == 'NBOMes' && @result1 == 'MAOIs'
      then final_value = 'Caut'
    elsif @result1 == 'NBOMes' && @result2 == 'SSRIs' || @result2 == 'NBOMes' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == '2C-x' &&  @result2 == 'LSD' || @result2 == '2C-x' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'Mushrooms' || @result2 == '2C-x' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'DMT' || @result2 == '2C-x' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'Mescaline' || @result2 == '2C-x' && @result1 == 'Mescaline'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == 'DOx' || @result2 == '2C-x' && @result1 == 'DOx'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == 'NBOMes' || @result2 == '2C-x' && @result1 == 'NBOMes'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == '2C-T-x' || @result2 == '2C-x' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == '5-MeO-xxT' || @result2 == '2C-x' && @result1 == '5-MeO-xxT'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == 'Cannabis' || @result2 == '2C-x' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == 'Ketamine' || @result2 == '2C-x' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'MXE' || @result2 == '2C-x' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'DXM' || @result2 == '2C-x' && @result1 == 'DXM'
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'Nitrous' || @result2 == '2C-x' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'Amphetamines' || @result2 == '2C-x' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == 'MDMA' || @result2 == '2C-x' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == '2C-x' && @result2 == 'Cocaine' || @result2 == '2C-x' && @result1 == 'Cocaine'
      then final_value = 'UNS'
    elsif @result1 == '2C-x' && @result2 == 'Caffeine' || @result2 == '2C-x' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == '2C-x' && @result2 == 'Alcohol' || @result2 == '2C-x' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == '2C-x' && @result2 == 'GBH/GBL' || @result2 == '2C-x' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == '2C-x' && @result2 == 'Opioids' || @result2 == '2C-x' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == '2C-x' && @result2 == 'Tramadol' || @result2 == '2C-x' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == '2C-x' && @result2 == 'Benzodiazepines' || @result2 == '2C-x' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == '2C-x' && @result2 == 'MAOIs' || @result2 == '2C-x' && @result1 == 'MAOIs'
      then final_value = 'Caut'
    elsif @result1 == '2C-x' && @result2 == 'SSRIs' || @result2 == '2C-x' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end
    
    if @result1 == '2C-T-x' &&  @result2 == 'LSD' || @result2 == '2C-T-x' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == '2C-T-x' && @result2 == 'Mushrooms' || @result2 == '2C-T-x' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == '2C-T-x' && @result2 == 'DMT' || @result2 == '2C-T-x' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == '2C-T-x' && @result2 == 'Mescaline' || @result2 == '2C-T-x' && @result1 == 'Mescaline'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'DOx' || @result2 == '2C-T-x' && @result1 == 'DOx'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'NBOMes' || @result2 == '2C-T-x' && @result1 == 'NBOMes'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == '2C-x' || @result2 == '2C-x' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == '5-MeO-xxT' || @result2 == '2C-T-x' && @result1 == '5-MeO-xxT'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'Cannabis' || @result2 == '2C-T-x' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'Ketamine' || @result2 == '2C-T-x' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == '2C-T-x' && @result2 == 'MXE' || @result2 == '2C-T-x' && @result1 == 'MXE'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'DXM' || @result2 == '2C-T-x' && @result1 == 'DXM'
      then final_value = 'UNS'
    elsif @result1 == '2C-T-x' && @result2 == 'Nitrous' || @result2 == '2C-T-x' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == '2C-T-x' && @result2 == 'Amphetamines' || @result2 == '2C-T-x' && @result1 == 'Amphetamines'
      then final_value = 'UNS'
    elsif @result1 == '2C-T-x' && @result2 == 'MDMA' || @result2 == '2C-T-x' && @result1 == 'MDMA' 
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'Cocaine' || @result2 == '2C-T-x' && @result1 == 'Cocaine'
      then final_value = 'UNS'
    elsif @result1 == '2C-T-x' && @result2 == 'Caffeine' || @result2 == '2C-T-x' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == '2C-T-x' && @result2 == 'Alcohol' || @result2 == '2C-T-x' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == '2C-T-x' && @result2 == 'GBH/GBL' || @result2 == '2C-T-x' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == '2C-T-x' && @result2 == 'Opioids' || @result2 == '2C-T-x' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == '2C-T-x' && @result2 == 'Tramadol' || @result2 == '2C-T-x' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == '2C-T-x' && @result2 == 'Benzodiazepines' || @result2 == '2C-T-x' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == '2C-T-x' && @result2 == 'MAOIs' || @result2 == '2C-T-x' && @result1 == 'MAOIs'
      then final_value = 'Caut'
    elsif @result1 == '2C-T-x' && @result2 == 'SSRIs' || @result2 == '2C-T-x' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == '5-Meo-xxT' &&  @result2 == 'LSD' || @result2 == '5-Meo-xxT' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Mushrooms' || @result2 == '5-Meo-xxT' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'DMT' || @result2 == '5-Meo-xxT' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Mescaline' || @result2 == '5-Meo-xxT' && @result1 == 'Mescaline'
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'DOx' || @result2 == '5-Meo-xxT' && @result1 == 'DOx'
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'NBOMes' || @result2 == '5-Meo-xxT' && @result1 == 'NBOMes'
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == '2C-x' || @result2 == '2C-x' && @result1 == '5-Meo-xxT'
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == '2C-T-x' || @result2 == '5-Meo-xxT' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Cannabis' || @result2 == '5-Meo-xxT' && @result1 == 'Cannabis' 
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Ketamine' || @result2 == '5-Meo-xxT' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'MXE' || @result2 == '5-Meo-xxT' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'DXM' || @result2 == '5-Meo-xxT' && @result1 == 'DXM'
      then final_value = 'UNS'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Nitrous' || @result2 == '5-Meo-xxT' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Amphetamines' || @result2 == '5-Meo-xxT' && @result1 == 'Amphetamines'
      then final_value = 'UNS'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'MDMA' || @result2 == '5-Meo-xxT' && @result1 == 'MDMA' 
      then final_value = 'Caut'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Cocaine' || @result2 == '5-Meo-xxT' && @result1 == 'Cocaine'
      then final_value = 'UNS'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Caffeine' || @result2 == '5-Meo-xxT' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Alcohol' || @result2 == '5-Meo-xxT' && @result1 == 'Alcohol'
      then final_value = 'LR&D'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'GBH/GBL' || @result2 == '5-Meo-xxT' && @result1 == 'GBH/GBL'
      then final_value = 'LR&D'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Opioids' || @result2 == '5-Meo-xxT' && @result1 == 'Opioids'
      then final_value = 'LR&NS'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Tramadol' || @result2 == '5-Meo-xxT' && @result1 == 'Tramadol'
      then final_value = 'UNS'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'Benzodiazepines' || @result2 == '5-Meo-xxT' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'MAOIs' || @result2 == '5-Meo-xxT' && @result1 == 'MAOIs'
      then final_value = 'DANG'
    elsif @result1 == '5-Meo-xxT' && @result2 == 'SSRIs' || @result2 == '5-Meo-xxT' && @result1 == 'SSRIs' 
      then final_value = 'LR&D'
    end

    if @result1 == 'Cannabis' &&  @result2 == 'LSD' || @result2 == 'Cannabis' &&  @result1 == 'LSD'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'Mushrooms' || @result2 == 'Cannabis' && @result1 == 'Mushrooms'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'DMT' || @result2 == 'Cannabis' && @result1 == 'DMT'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'Mescaline' || @result2 == 'Cannabis' && @result1 == 'Mescaline'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'DOx' || @result2 == 'Cannabis' && @result1 == 'DOx'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'NBOMes' || @result2 == 'Cannabis' && @result1 == 'NBOMes'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == '2C-x' || @result2 == '2C-x' && @result1 == 'Cannabis'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == '2C-T-x' || @result2 == 'Cannabis' && @result1 == '2C-T-x'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == '5-MeO-xxT' || @result2 == 'Cannabis' && @result1 == '5-MeO-xxt' 
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'Ketamine' || @result2 == 'Cannabis' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'MXE' || @result2 == 'Cannabis' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'DXM' || @result2 == 'Cannabis' && @result1 == 'DXM'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'Nitrous' || @result2 == 'Cannabis' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'Amphetamines' || @result2 == 'Cannabis' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'MDMA' || @result2 == 'Cannabis' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'Cocaine' || @result2 == 'Cannabis' && @result1 == 'Cocaine'
      then final_value = 'Caut'
    elsif @result1 == 'Cannabis' && @result2 == 'Caffeine' || @result2 == 'Cannabis' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == 'Cannabis' && @result2 == 'Alcohol' || @result2 == 'Cannabis' && @result1 == 'Alcohol'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'GBH/GBL' || @result2 == 'Cannabis' && @result1 == 'GBH/GBL'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'Opioids' || @result2 == 'Cannabis' && @result1 == 'Opioids'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'Tramadol' || @result2 == 'Cannabis' && @result1 == 'Tramadol'
      then final_value = 'LR&S'
    elsif @result1 == 'Cannabis' && @result2 == 'Benzodiazepines' || @result2 == 'Cannabis' && @result1 == 'Benzodiazepines'
      then final_value = 'LR&D'
    elsif @result1 == 'Cannabis' && @result2 == 'MAOIs' || @result2 == 'Cannabis' && @result1 == 'MAOIs'
      then final_value = 'LR&D'
    elsif @result1 == 'Cannabis' && @result2 == 'SSRIs' || @result2 == 'Cannabis' && @result1 == 'SSRIs' 
      then final_value = 'LR&NS'
    end

    if @result1 == 'Ketamine' &&  @result2 == 'LSD' || @result2 == 'Ketamine' &&  @result1 == 'LSD'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'Mushrooms' || @result2 == 'Ketamine' && @result1 == 'Mushrooms'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'DMT' || @result2 == 'Ketamine' && @result1 == 'DMT'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'Mescaline' || @result2 == 'Ketamine' && @result1 == 'Mescaline'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'DOx' || @result2 == 'Ketamine' && @result1 == 'DOx'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'NBOMes' || @result2 == 'Ketamine' && @result1 == 'NBOMes'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == '2C-x' || @result2 == '2C-x' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == '2C-T-x' || @result2 == 'Ketamine' && @result1 == '2C-T-x'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == '5-MeO-xxT' || @result2 == 'Ketamine' && @result1 == '5-MeO-xxt' 
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'Cannabis' || @result2 == 'Cannabis' && @result1 == 'Ketamine'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'MXE' || @result2 == 'Ketamine' && @result1 == 'MXE'
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'DXM' || @result2 == 'Ketamine' && @result1 == 'DXM'
      then final_value = 'LR&NS'
    elsif @result1 == 'Ketamine' && @result2 == 'Nitrous' || @result2 == 'Ketamine' && @result2 == 'Nitrous'
      then final_value == 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'Amphetamines' || @result2 == 'Ketamine' && @result1 == 'Amphetamines'
      then final_value = 'Caut'
    elsif @result1 == 'Ketamine' && @result2 == 'MDMA' || @result2 == 'Ketamine' && @result1 == 'MDMA' 
      then final_value = 'LR&S'
    elsif @result1 == 'Ketamine' && @result2 == 'Cocaine' || @result2 == 'Ketamine' && @result1 == 'Cocaine'
      then final_value = 'Caut'
    elsif @result1 == 'Ketamine' && @result2 == 'Caffeine' || @result2 == 'Ketamine' && @result1 == 'Caffeine'
      then final_value = 'LR&NS'
    elsif @result1 == 'Ketamine' && @result2 == 'Alcohol' || @result2 == 'Ketamine' && @result1 == 'Alcohol'
      then final_value = 'DANG'
    elsif @result1 == 'Ketamine' && @result2 == 'GBH/GBL' || @result2 == 'Ketamine' && @result1 == 'GBH/GBL'
      then final_value = 'DANG'
    elsif @result1 == 'Ketamine' && @result2 == 'Opioids' || @result2 == 'Ketamine' && @result1 == 'Opioids'
      then final_value = 'DANG'
    elsif @result1 == 'Ketamine' && @result2 == 'Tramadol' || @result2 == 'Ketamine' && @result1 == 'Tramadol'
      then final_value = 'DANG'
    elsif @result1 == 'Ketamine' && @result2 == 'Benzodiazepines' || @result2 == 'Ketamine' && @result1 == 'Benzodiazepines'
      then final_value = 'Caut'
    elsif @result1 == 'Ketamine' && @result2 == 'MAOIs' || @result2 == 'Ketamine' && @result1 == 'MAOIs'
      then final_value = 'Caut'
    elsif @result1 == 'Ketamine' && @result2 == 'SSRIs' || @result2 == 'Ketamine' && @result1 == 'SSRIs' 
      then final_value = 'LR&NS'
    end


    if final_value == "LR&S"
      then @print_value = "Low Risk & Synergy"
    elsif final_value = "Caut"
      then @print_value = "Caution!"
    end

      require 'net/http'
      require 'uri'
      require 'json'

      uri = URI.parse("https://api.psychonautwiki.org/")
      request = Net::HTTP::Post.new(uri)
      request.content_type = "application/json"
      request["Accept"] = "application/json"
      request["Connection"] = "keep-alive"
      request["Dnt"] = "1"
      request["Origin"] = "https://api.psychonautwiki.org"
      request.body = JSON.dump({
        "query" => "{ substances { name } }"
      })

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end
      response = JSON.parse(response.body)
      response = response.fetch("data").fetch('substances')
      arrayed = []
      response = response.each_with_index do |this, index|
        arrayed.push(this.fetch('name'))
      end

      @parsed_data = arrayed

      render({ :template => 'results.html.erb'})
    
  end
end
